import React, { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, BookOpen, Brain, Check, ClipboardList, Heart, Sparkles } from "lucide-react";
import { createRoadmap, getStudentOverview, saveStudentAssessment, saveStudentCheckin, saveStudentProfile, updateStudentTask } from "./api";

const initialProfile = { institution: "", board: "", semester: "", course: "", subjects: "", exam_date: "", study_hours: 2, career_goal: "" };
const initialAssessment = { completed_topics: 0, total_topics: 10, difficult_topics: "", learning_style: "mixed", focus: 3, motivation: 3, stress: 3, sleep: 3, time_management: 3, procrastination: 3 };
const labels = { focus: "Focus", motivation: "Motivation", stress: "Exam stress", sleep: "Sleep quality", time_management: "Time management", procrastination: "Procrastination" };

function Score({ label, value }) { return <article className="student-score"><span>{label}</span><strong>{value}%</strong><i><b style={{ width: `${value}%` }} /></i></article>; }
function Scale({ label, value, onChange }) { return <label className="student-scale"><span>{label}<b>{value}/5</b></span><input type="range" min="1" max="5" value={value} onChange={(event) => onChange(Number(event.target.value))} /><small>Needs support <em /> Going well</small></label>; }

export default function StudentSuccess({ token, user, onHome, onChat, onSignIn, onSessionExpired }) {
  const [overview, setOverview] = useState(null); const [view, setView] = useState("loading"); const [profile, setProfile] = useState(initialProfile); const [assessment, setAssessment] = useState(initialAssessment); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const [checkin, setCheckin] = useState(""); const [message, setMessage] = useState("");
  const name = user?.name?.split(" ")[0] || "there";
  const load = async () => { if (!token) { onSignIn(); return; } try { const data = await getStudentOverview(token); setOverview(data); if (!data.profile) setView("profile"); else if (!data.assessment) setView("assessment"); else setView("dashboard"); } catch (err) { if (err.status === 401) onSessionExpired(); else setError(err.message); } };
  useEffect(() => { load(); }, []);
  const submitProfile = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { await saveStudentProfile(token, { ...profile, subjects: profile.subjects.split(",").map((x) => x.trim()).filter(Boolean), exam_date: profile.exam_date || null, study_hours: Number(profile.study_hours) }); await load(); } catch (err) { setError(err.message); } finally { setSaving(false); } };
  const submitAssessment = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { await saveStudentAssessment(token, { ...assessment, difficult_topics: assessment.difficult_topics.split(",").map((x) => x.trim()).filter(Boolean) }); await load(); } catch (err) { setError(err.message); } finally { setSaving(false); } };
  const generateRoadmap = async () => { setSaving(true); try { await createRoadmap(token); await load(); } catch (err) { setError(err.message); } finally { setSaving(false); } };
  const toggleTask = async (task) => { await updateStudentTask(token, task._id, !task.completed); await load(); };
  const mood = async (value) => { setCheckin(value); try { const result = await saveStudentCheckin(token, { mood: value }); setMessage(result.guidance); await load(); } catch (err) { setError(err.message); } };
  if (view === "loading") return <main className="student-page"><p className="student-loading">Opening your Student Success space…</p></main>;
  if (view === "profile") return <main className="student-page"><StudentNav onHome={onHome} /><section className="student-form-shell"><p className="student-kicker">STUDENT SUCCESS</p><h1>Let’s build a plan around your real semester.</h1><p>Share only what helps HOPEMO personalize your learning support.</p><form onSubmit={submitProfile} className="student-form"><input required placeholder="School or college" value={profile.institution} onChange={(e) => setProfile({ ...profile, institution: e.target.value })} /><input required placeholder="Board / university (e.g. KTU, CBSE)" value={profile.board} onChange={(e) => setProfile({ ...profile, board: e.target.value })} /><input required placeholder="Semester or class" value={profile.semester} onChange={(e) => setProfile({ ...profile, semester: e.target.value })} /><input required placeholder="Course" value={profile.course} onChange={(e) => setProfile({ ...profile, course: e.target.value })} /><input required placeholder="Subjects, separated by commas" value={profile.subjects} onChange={(e) => setProfile({ ...profile, subjects: e.target.value })} /><label>Next exam date <input type="date" value={profile.exam_date} onChange={(e) => setProfile({ ...profile, exam_date: e.target.value })} /></label><label>Typical study hours per day <input type="number" min="0.25" max="16" step="0.25" value={profile.study_hours} onChange={(e) => setProfile({ ...profile, study_hours: e.target.value })} /></label><input placeholder="Career goal (optional)" value={profile.career_goal} onChange={(e) => setProfile({ ...profile, career_goal: e.target.value })} />{error && <p className="student-error">{error}</p>}<button className="blue-pill" disabled={saving}>{saving ? "Saving…" : "Continue to assessment"}<ArrowRight /></button></form></section></main>;
  if (view === "assessment") return <main className="student-page"><StudentNav onHome={onHome} /><section className="student-form-shell"><p className="student-kicker">YOUR LEARNING SNAPSHOT</p><h1>What would make studying feel more manageable?</h1><p>This is a planning check-in, not a medical or academic diagnosis.</p><form onSubmit={submitAssessment} className="student-form student-assessment"><div className="student-pair"><label>Topics completed <input type="number" min="0" max="100" value={assessment.completed_topics} onChange={(e) => setAssessment({ ...assessment, completed_topics: Number(e.target.value) })} /></label><label>Total topics <input type="number" min="1" max="100" value={assessment.total_topics} onChange={(e) => setAssessment({ ...assessment, total_topics: Number(e.target.value) })} /></label></div><input placeholder="Difficult topics, separated by commas" value={assessment.difficult_topics} onChange={(e) => setAssessment({ ...assessment, difficult_topics: e.target.value })} /><label>Preferred learning style <select value={assessment.learning_style} onChange={(e) => setAssessment({ ...assessment, learning_style: e.target.value })}><option value="mixed">Mixed</option><option value="visual">Visual</option><option value="reading">Reading</option><option value="practical">Practical</option></select></label>{Object.entries(labels).map(([key, label]) => <Scale key={key} label={label} value={assessment[key]} onChange={(value) => setAssessment({ ...assessment, [key]: value })} />)}{error && <p className="student-error">{error}</p>}<button className="blue-pill" disabled={saving}>{saving ? "Creating your report…" : "See my learning report"}<ArrowRight /></button></form></section></main>;
  const scores = overview.assessment.scores; const tasks = overview.tasks || []; const done = tasks.filter((task) => task.completed).length;
  return <main className="student-page"><StudentNav onHome={onHome} /><section className="student-dashboard"><div className="student-welcome"><div><p className="student-kicker">YOUR STUDENT COMPANION</p><h1>Good to see you, {name}.</h1><p>{overview.profile.course} · {overview.profile.semester} · {overview.profile.institution}</p></div><button className="blue-pill" onClick={onChat}><Sparkles /> Talk to Student Coach</button></div><div className="student-grid"><section className="student-card student-readiness"><p>EXAM READINESS</p><strong>{scores.exam_readiness}<small>%</small></strong><span>Planning estimate based on your progress and routines—not a grade prediction.</span><button onClick={generateRoadmap} disabled={saving}>{tasks.length ? "Refresh 7-day roadmap" : "Create my 7-day roadmap"} <ArrowRight /></button></section><section className="student-card"><p>TODAY’S PLAN</p><h2>{done}/{tasks.length} tasks completed</h2>{tasks.length ? <div className="student-task-list">{tasks.map((task) => <button className={task.completed ? "complete" : ""} key={task._id} onClick={() => toggleTask(task)}><i>{task.completed && <Check />}</i><span>{task.title}<small>{task.minutes} minutes · {task.kind}</small></span></button>)}</div> : <p className="student-muted">Create your roadmap to receive a focused first-week plan.</p>}</section><section className="student-card student-checkin"><p>DAILY WELLBEING CHECK-IN</p><h2>How are you feeling today?</h2><div>{[["happy", "😊", "Happy"], ["okay", "😐", "Okay"], ["stressed", "😔", "Stressed"], ["tired", "😴", "Tired"]].map(([value, icon, label]) => <button className={checkin === value || overview.checkin?.mood === value ? "selected" : ""} key={value} onClick={() => mood(value)}><b>{icon}</b>{label}</button>)}</div>{message && <aside><Heart /> {message}</aside>}</section></div><section className="student-scores"><Score label="Academic readiness" value={scores.academic_readiness} /><Score label="Focus" value={scores.focus} /><Score label="Time management" value={scores.time_management} /><Score label="Overall wellness" value={scores.wellness} /></section><section className="student-coach-callout"><Brain /><div><p>STUDENT COACH IS READY</p><h2>Your regular HOPEMO chat now has an optional study-aware mode.</h2><span>It uses your own plan, learning preference, difficult topics, and today’s tasks only when you choose Student Coach.</span></div><button onClick={onChat}>Open coach <ArrowRight /></button></section></section></main>;
}

function StudentNav({ onHome }) { return <nav className="student-nav"><button className="page-back" onClick={onHome}><ArrowLeft /> Back to home</button><img src="/hopemo-wordmark.jpg" alt="HOPEMO" /><span><BookOpen /> Student Success</span></nav>; }
